site_name: Pesquisa e Novação
repo_url: https://github.com/pesquisa-novacao/pesquisa-novacao.github.io
theme:
  name: material
  features:
    - navigation.tabs
  language: pt
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Sobre: 
    - index.md
  - Material:
    - material.md
    - material/cobertura-imprensa.md
    - material/textos.md
  - comunidades.md
  - auxilio-juridico.md
  - CONTRIBUTING.md
  - SUPPORT.md
